spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/smartcity
    username: root
    password: 1tvictor
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true